### ISSUE TITLE
Merging and reconciling .vs1 files.

### ISSUE THREAD

**Issue by BitSniffing** [RIEI/Vistumbler#3]
Other than developing a backend process, does Vistumbler perform any merging and reconciling of multiple .vs1 files?

**Comment by acalcutt** [comment]
When importing multiple vs1 files into vistumbler the signal and gps histories are merged, but if you have a lot of files vistumbler is going to start to get slow. This is why we created the WiFiDB (http://live.wifidb.net), which is a open source database to store multiple vistumbler files with history.

If you are talking about combining multiple VS1 files outside vistumbler (like through a text editor) you may have problems with conflicting gps ids since different files will likely have conflicting ids (see the VS1 format info here https://github.com/RIEI/Vistumbler/wiki/Vistumbler-VS1-Format ). If you wanted to do that type of text based merging of files you may be better off using our detailed csv format, which you should be able to combine multiple files into one by just combining the together.

**Comment by acalcutt** [comment]
I also create a batch VS1 importer for a user on the forums here ( https://forum.techidiots.net/forum/viewtopic.php?f=8&t=2010&hilit=ImportVS1 )

The code for that importer is here ( https://github.com/RIEI/Vistumbler/tree/beta/BatchImportVS1 )

**Comment by BitSniffing** [comment]
Sorry about that.  Still learning the application.  Thanks for the help.
